translations = {
    ('pt', 'en'): {
        'Olá': 'Hello', 'Mundo': 'World', 'Bom': 'Good', 'Dia': 'Day', 'Café': 'Coffee', 'Trabalho': 'Work',
        'Casa': 'House', 'Amigo': 'Friend', 'Feliz': 'Happy', 'Comida': 'Food', 'Computador': 'Computer',
        'Escola': 'School', 'Livro': 'Book', 'Carro': 'Car', 'Cachorro': 'Dog', 'Gato': 'Cat',
        'Amor': 'Love', 'Tempo': 'Time', 'Música': 'Music', 'Filme': 'Movie', 'Viagem': 'Travel',
        'Azul': 'Blue', 'Verde': 'Green', 'Vermelho': 'Red', 'Amarelo': 'Yellow', 'Laranja': 'Orange',
        'Céu': 'Sky', 'Água': 'Water', 'Pão': 'Bread', 'Fruta': 'Fruit', 'Chuva': 'Rain',
        'Sol': 'Sun', 'Lua': 'Moon', 'Estrela': 'Star', 'Família': 'Family', 'Trabalho': 'Job',
        'Estudo': 'Study', 'Criança': 'Child', 'Mãe': 'Mother', 'Pai': 'Father', 'Irmão': 'Brother',
        'Irmã': 'Sister', 'Avô': 'Grandfather', 'Avó': 'Grandmother', 'Esporte': 'Sport', 'Amizade': 'Friendship',
    },
    ('pt', 'es'): {
        'Olá': 'Hola', 'Mundo': 'Mundo', 'Bom': 'Bueno', 'Dia': 'Día', 'Café': 'Café', 'Trabalho': 'Trabajo',
        'Casa': 'Casa', 'Amigo': 'Amigo', 'Feliz': 'Feliz', 'Comida': 'Comida', 'Computador': 'Computadora',
        'Escola': 'Escuela', 'Livro': 'Libro', 'Carro': 'Auto', 'Cachorro': 'Perro', 'Gato': 'Gato',
        'Amor': 'Amor', 'Tempo': 'Tiempo', 'Música': 'Música', 'Filme': 'Película', 'Viagem': 'Viaje',
        'Azul': 'Azul', 'Verde': 'Verde', 'Vermelho': 'Rojo', 'Amarelo': 'Amarillo', 'Laranja': 'Naranja',
        'Céu': 'Cielo', 'Água': 'Agua', 'Pão': 'Pan', 'Fruta': 'Fruta', 'Chuva': 'Lluvia',
        'Sol': 'Sol', 'Lua': 'Luna', 'Estrela': 'Estrella', 'Família': 'Familia', 'Trabalho': 'Trabajo',
        'Estudo': 'Estudio', 'Criança': 'Niño', 'Mãe': 'Madre', 'Pai': 'Padre', 'Irmão': 'Hermano',
        'Irmã': 'Hermana', 'Avô': 'Abuelo', 'Avó': 'Abuela', 'Esporte': 'Deporte', 'Amizade': 'Amistad',
    },
    ('pt', 'fr'): {
        'Olá': 'Bonjour', 'Mundo': 'Monde', 'Bom': 'Bien', 'Dia': 'Jour', 'Café': 'Café', 'Trabalho': 'Travail',
        'Casa': 'Maison', 'Amigo': 'Ami', 'Feliz': 'Heureux', 'Comida': 'Nourriture', 'Computador': 'Ordinateur',
        'Escola': 'École', 'Livro': 'Livre', 'Carro': 'Voiture', 'Cachorro': 'Chien', 'Gato': 'Chat',
        'Amor': 'Amour', 'Tempo': 'Temps', 'Música': 'Musique', 'Filme': 'Film', 'Viagem': 'Voyage',
        'Azul': 'Bleu', 'Verde': 'Vert', 'Vermelho': 'Rouge', 'Amarelo': 'Jaune', 'Laranja': 'Orange',
        'Céu': 'Ciel', 'Água': 'Eau', 'Pão': 'Pain', 'Fruta': 'Fruit', 'Chuva': 'Pluie',
        'Sol': 'Soleil', 'Lua': 'Lune', 'Estrela': 'Étoile', 'Família': 'Famille', 'Trabalho': 'Travail',
        'Estudo': 'Étude', 'Criança': 'Enfant', 'Mãe': 'Mère', 'Pai': 'Père', 'Irmão': 'Frère',
        'Irmã': 'Soeur', 'Avô': 'Grand-père', 'Avó': 'Grand-mère', 'Esporte': 'Sport', 'Amizade': 'Amitié',
    },
    ('pt', 'ko'): {
        'Olá': '안녕하세요', 'Mundo': '세계', 'Bom': '좋은', 'Dia': '날', 'Café': '커피', 'Trabalho': '일',
        'Casa': '집', 'Amigo': '친구', 'Feliz': '행복한', 'Comida': '음식', 'Computador': '컴퓨터',
        'Escola': '학교', 'Livro': '책', 'Carro': '차', 'Cachorro': '개', 'Gato': '고양이',
        'Amor': '사랑', 'Tempo': '시간', 'Música': '음악', 'Filme': '영화', 'Viagem': '여행',
        'Azul': '파란', 'Verde': '녹색', 'Vermelho': '빨간', 'Amarelo': '노란', 'Laranja': '주황',
        'Céu': '하늘', 'Água': '물', 'Pão': '빵', 'Fruta': '과일', 'Chuva': '비',
        'Sol': '태양', 'Lua': '달', 'Estrela': '별', 'Família': '가족', 'Trabalho': '일',
        'Estudo': '공부', 'Criança': '어린이', 'Mãe': '엄마', 'Pai': '아빠', 'Irmão': '형제',
        'Irmã': '자매', 'Avô': '할아버지', 'Avó': '할머니', 'Esporte': '운동', 'Amizade': '친구',
    },
    ('pt', 'ja'): {
        'Olá': 'こんにちは', 'Mundo': '世界', 'Bom': '良い', 'Dia': '日', 'Café': 'コーヒー', 'Trabalho': '仕事',
        'Casa': '家', 'Amigo': '友達', 'Feliz': '幸せ', 'Comida': '食べ物', 'Computador': 'コンピューター',
        'Escola': '学校', 'Livro': '本', 'Carro': '車', 'Cachorro': '犬', 'Gato': '猫',
        'Amor': '愛', 'Tempo': '時間', 'Música': '音楽', 'Filme': '映画', 'Viagem': '旅行',
        'Azul': '青', 'Verde': '緑', 'Vermelho': '赤', 'Amarelo': '黄色', 'Laranja': 'オレンジ',
        'Céu': '空', 'Água': '水', 'Pão': 'パン', 'Fruta': '果物', 'Chuva': '雨',
        'Sol': '太陽', 'Lua': '月', 'Estrela': '星', 'Família': '家族', 'Trabalho': '仕事',
        'Estudo': '勉強', 'Criança': '子供', 'Mãe': 'お母さん', 'Pai': 'お父さん', 'Irmão': '兄弟',
        'Irmã': '姉妹', 'Avô': 'おじいさん', 'Avó': 'おばあさん', 'Esporte': 'スポーツ', 'Amizade': '友情',
    },
    ('pt', 'zh'): {
        'Olá': '你好', 'Mundo': '世界', 'Bom': '好的', 'Dia': '天', 'Café': '咖啡', 'Trabalho': '工作',
        'Casa': '家', 'Amigo': '朋友', 'Feliz': '快乐', 'Comida': '食物', 'Computador': '计算机',
        'Escola': '学校', 'Livro': '书', 'Carro': '车', 'Cachorro': '狗', 'Gato': '猫',
        'Amor': '爱', 'Tempo': '时间', 'Música': '音乐', 'Filme': '电影', 'Viagem': '旅行',
        'Azul': '蓝色', 'Verde': '绿色', 'Vermelho': '红色', 'Amarelo': '黄色', 'Laranja': '橙色',
        'Céu': '天空', 'Água': '水', 'Pão': '面包', 'Fruta': '水果', 'Chuva': '雨',
        'Sol': '太阳', 'Lua': '月亮', 'Estrela': '星星', 'Família': '家庭', 'Trabalho': '工作',
        'Estudo': '学习', 'Criança': '孩子', 'Mãe': '妈妈', 'Pai': '爸爸', 'Irmão': '兄弟',
        'Irmã': '姐妹', 'Avô': '爷爷', 'Avó': '奶奶', 'Esporte': '运动', 'Amizade': '友谊',
    },
}
